# Generated by Django 5.2.17 on 2026-09-11 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOMVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, verbose_name='版本号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=16, verbose_name='状态')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['product_id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='物料编码')),
                ('name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('spec', models.CharField(blank=True, default='', max_length=128, verbose_name='规格')),
                ('unit', models.CharField(default='PCS', max_length=16, verbose_name='单位')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='产品编码')),
                ('name', models.CharField(max_length=128, verbose_name='产品名称')),
            ],
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='用量')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='同级序号')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bom.bomline')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bom.bomversion')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='bom.material')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='bomversion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='bom.product'),
        ),
        migrations.CreateModel(
            name='SubstituteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_start', models.PositiveIntegerField(verbose_name='起始序列号')),
                ('serial_end', models.PositiveIntegerField(verbose_name='截止序列号')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_as_original', to='bom.material')),
                ('substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_as_substitute', to='bom.material')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='bom.bomversion')),
            ],
            options={
                'ordering': ['original_id', 'serial_start', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField(verbose_name='产品序列号')),
                ('snapshot', models.JSONField(verbose_name='发料时刻解析快照')),
                ('operator', models.CharField(blank=True, default='', max_length=64, verbose_name='操作人')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='bom.bomversion')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='bom.product')),
            ],
            options={
                'ordering': ['serial_no'],
                'unique_together': {('product', 'serial_no')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bomversion',
            unique_together={('product', 'version')},
        ),
    ]
